services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=lizmark
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes: [ './postgres_data:/var/lib/postgresql/data' ]
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    ports:
      - 5050:80

  mysql:
    image: mariadb:10.5 # A version with better ARM64 support
    platform: linux/arm64
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3306:3306
    volumes: [ './mysql_data:/var/lib/mysql' ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64 # Forzar amd64
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - PMA_HOST=mysql
    ports:
      - 8080:80
